### ISSUE TITLE
Poggit download doesn't do anything

### ISSUE THREAD

**Issue by n00bslayr94** [iLVOEWOCK/AdvancedBounty#1]
Downloaded the .phar and converted the zip to .phar. Plugin shows as "loaded" when running /plugins command but the plugin data file isn't populating with the config file. Something isn't right?

**Comment by iLVOEWOCK** [comment]
Can you tell me what happens when you give someone a bounty?

**Comment by iLVOEWOCK** [comment]
i just tested, seems the entire plugin doesnt work anymore, including commands, give me a minute

**Comment by iLVOEWOCK** [comment]
Fixed in the latest version, You may use the main branch if youd like or wait for poggit to release the update!
